Metadata
stratis-storage/stratis-cli pull request #1023
Opened 2023-09-15 01:02 UTC by mulkieran

2023-09-15 01:08 UTC, mulkieran commented
Expect some pool listing tests to fail...

2023-09-15 01:28 UTC, mulkieran commented
should succeed w/ redirect

2023-09-15 11:59 UTC, bgurney-rh commented
/packit build

2024-05-22 20:42 UTC, mulkieran commented
rebased

2024-05-30 17:00 UTC, mulkieran commented
Passed against updated D-Bus API...

2024-06-04 03:15 UTC, mulkieran commented
expect coverage test to fail...

2024-07-12 16:22 UTC, mulkieran commented
/packit build

2024-07-15 20:34 UTC, mulkieran commented
/packit build

2024-07-18 20:20 UTC, drckeefe approved these changes

2024-07-18 21:04 UTC, bgurney-rh approved these changes

2024-07-19 12:44 UTC, bmr-cymru approved these changes

2024-07-19 18:29 UTC, jbaublitz requested changes
After testing I don't think I have any problems with the code, just one note on documentation that could be a little bit clearer.

2024-07-19 18:29 UTC, jbaublitz commented on docs/stratis.txt
> +     only the passphrase and method specified, so that the pool will not be
Maybe "and the keyslot corresponding to the method specified"

2024-07-22 14:23 UTC, mulkieran commented
@jbaublitz Ok. I've modified the man page to try to make the pool start rules clearer. Let me know what you think.

2024-07-22 14:24 UTC, jbaublitz approved these changes

2024-07-22 17:55 UTC, mulkieran commented
/packit build

2024-07-22 18:09 UTC, merged