Add debug command to get filesystem metadata
stratis-storage/stratis-cli pull request #1089
Opened 2024-07-26 02:29 UTC by mulkieran

2024-07-31 18:53 UTC, mulkieran commented
@drckeefe @bmr-cymru Please take a look and let me know if you feel satisfied w/ the command-line arguments for the get-metadata call.

2024-07-31 20:02 UTC, drckeefe approved these changes

2024-08-01 18:33 UTC, jbaublitz requested changes
There might be one change required due to the stratisd side.

2024-08-01 18:33 UTC, jbaublitz commented on src/stratis_cli/_actions/_debug.py
> +        ]
This will have to change if the stratisd side changes.

2024-08-01 20:10 UTC, jbaublitz approved these changes

2024-08-02 13:52 UTC, mulkieran commented
/packit build

2024-08-02 16:52 UTC, merged