blackbox: add rename test to test_filesystem_udev_symlink
stratis-storage/stratis-cli pull request #668
Opened 2020-10-28 19:32 UTC by bgurney-rh

Related: #667

2020-10-28 19:35 UTC, bgurney-rh commented
This isn't quite complete, because I have this block of code that's used twice in test_filesystem_udev_symlink, and I feel like part (or all) of it could become a helper function, perhaps in StratisDbus:
```
        objects = StratisDbus.get_managed_objects()

        pool_gmodata = objects[pool_path]
        pool_uuid = pool_gmodata[StratisDbus.POOL_IFACE]["Uuid"]
        filesystem_gmodata = objects[filesystem_path]
        filesystem_uuid = filesystem_gmodata[StratisDbus.FS_IFACE]["Uuid"]

        filesystem_devnode = filesystem_gmodata[StratisDbus.FS_IFACE]["Devnode"]
  
        fs_devmapperlinkstr = (
            "/dev/mapper/stratis-1-" + pool_uuid + "-thin-fs-" + filesystem_uuid
        )

        fsdevdest = resolve_symlink(filesystem_devnode)
        fsdevmapperlinkdest = resolve_symlink(fs_devmapperlinkstr)
```

Out of the code block above, is there something that looks like it could become a good helper function?

(I could probably also use better variable names, and/or a cleanup on how the objects are accessed.)

2020-10-29 15:59 UTC, mulkieran commented
> This isn't quite complete, because I have this block of code that's used twice in test_filesystem_udev_symlink, and I feel like part (or all) of it could become a helper function, perhaps in StratisDbus:
> 
> ```
>         objects = StratisDbus.get_managed_objects()
> 
>         pool_gmodata = objects[pool_path]
>         pool_uuid = pool_gmodata[StratisDbus.POOL_IFACE]["Uuid"]
>         filesystem_gmodata = objects[filesystem_path]
>         filesystem_uuid = filesystem_gmodata[StratisDbus.FS_IFACE]["Uuid"]
> 
>         filesystem_devnode = filesystem_gmodata[StratisDbus.FS_IFACE]["Devnode"]
>   
>         fs_devmapperlinkstr = (
>             "/dev/mapper/stratis-1-" + pool_uuid + "-thin-fs-" + filesystem_uuid
>         )
> 
>         fsdevdest = resolve_symlink(filesystem_devnode)
>         fsdevmapperlinkdest = resolve_symlink(fs_devmapperlinkstr)
> ```
> 
> Out of the code block above, is there something that looks like it could become a good helper function?
> 
> (I could probably also use better variable names, and/or a cleanup on how the objects are accessed.)

You definitely should look at making this into a helper function. The way I'ld do it, at least to start,
is try to figure out what identifiers are local to the block and what aren't. If it's local to the code
block, that means it gets a value in the code block, and only that value is used, and after the end
of the code block it's not used anymore. So, ```objects``` is a good example of something that's
local. It gets a value in the assignment ```objects = StratisDbus.get_managed_objects()```, and
the value is used in the code block, but it isn't used at all after the code block. So ```objects```
would be local to the function made from that code block. ```pool_path```, though, is not local,
because the value is assigned to it before the code block is entered. So, ```pool_path``` would
be a parameter to a function made from the code block, but ```objects``` would not, it would just
be local to that function.

You might have to adjust the start or end of your code block to make the function as useful as possible.

The way to think about where the function should end is often to think about what the return value should
be. What would be the most useful thing to return from this function, if anything?

2020-11-02 18:01 UTC, mulkieran reviewed
This looks good! Try adding the additional step of changing the pool name.

2020-11-03 00:19 UTC, mulkieran requested changes
This looks great! But, I think to be consistent w/ our nearly only one assertion per test rule, we should break this test up into three tests: one test just to make the filesystem and check the symlinks, one test to make the filesystem, rename it, and test the symlinks, and one test to make the filesytem, rename the pool, and test the filesystem symlinks. I think you should be able to reuse every helper function you've already written quite well.

2020-11-03 13:11 UTC, bgurney-rh commented
OK, that makes sense.  Do we want to create four tests, for each of the four states?
- Test symlinks after creation (no renames)
- Test symlinks after creation and fs rename
- Test symlinks after creation and pool rename
- Test symlinks after creation, pool rename, and fs rename

2020-11-03 14:47 UTC, mulkieran commented
> OK, that makes sense. Do we want to create four tests, for each of the four states?
> 
>     * Test symlinks after creation (no renames)
> 
>     * Test symlinks after creation and fs rename
> 
>     * Test symlinks after creation and pool rename
> 
>     * Test symlinks after creation, pool rename, and fs rename

Yes. That seems good.

2020-11-03 15:22 UTC, mulkieran requested changes
This looks good. I've asked you to drop certain checks, because they can be viewed as redundant. 

After that, this PR should be ready to go.

2020-11-03 15:22 UTC, mulkieran commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
You can drop the check here.

2020-11-03 15:22 UTC, mulkieran commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
And drop it here.

2020-11-03 15:22 UTC, mulkieran commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
And here.

2020-11-03 15:35 UTC, bgurney-rh commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
Resolved.

2020-11-03 15:36 UTC, bgurney-rh commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
Resolved.

2020-11-03 15:36 UTC, bgurney-rh commented on tests/blackbox/stratisd_cert.py
> +        fsdevdest, fsdevmapperlinkdest = acquire_filesystem_symlink_targets(
Resolved.

2020-11-03 15:51 UTC, mulkieran requested changes
I think this is ready to go. Please close this PR and open a new one for final review.

2020-11-03 16:04 UTC, closed without merging