Call the EngineStateReport via Manager method
stratis-storage/stratis-cli pull request #701
Opened 2021-01-14 15:51 UTC by lleshchi

Closes: https://github.com/stratis-storage/stratis-cli/issues/700

2021-01-14 15:52 UTC, lleshchi commented
@mulkieran If this looks good, I will continue on with tests and man pages

2021-01-14 16:16 UTC, mulkieran commented
@lleshchi Just explicitly allow the bad-continuation errors. black is correct, pylint is wrong.

2021-01-14 16:24 UTC, mulkieran commented on src/stratis_cli/_actions/_top.py
> +        if (
```report_name``` will always have some non-```None``` value, due to the parser change. So it's not necessary to check for it here.

2021-01-14 16:26 UTC, mulkieran requested changes
That's all I see. You should be able to carry on w/ the rest of the steps after fixing those.

2021-01-14 16:49 UTC, jbaublitz reviewed
Other than @mulkieran's request, this looks good to me so far!

2021-01-15 16:59 UTC, lleshchi commented
@mulkieran The `get_report()` and `get_engine_state_report()` methods in testlib/dbus.py can be condensed into one method in order to satisfy the pylint error "too-many-public-methods" or error can be ignored

2021-01-15 17:03 UTC, mulkieran commented
> @mulkieran The `get_report()` and `get_engine_state_report()` methods in testlib/dbus.py can be condensed into one method in order to satisfy the pylint error "too-many-public-methods" or error can be ignored

@lleshchi: I'm fine if you disable the warning. I think the code is simpler as it is.

2021-01-20 00:30 UTC, mulkieran requested changes
Two final requests...otherwise it looks ready.

2021-01-20 00:30 UTC, mulkieran commented on src/stratis_cli/_parser/_parser.py
> +                        nargs="?",
Please add a `choices` parameter here as well with the two available names, ```engine_state_report``` and ```errored_pool_report```.

2021-01-20 00:30 UTC, mulkieran commented on docs/stratis.txt
> +        Get engine_state_report if no report name is provided. This command only
What we want here is to indicate which names are stable and which aren't, but making a list of 1 is unappealing.

Maybe say something like:

The `engine_state_report` name will be supported in future releases. Any other report name should be considered unstable and may be removed in a future release. The JSON schema of any report must always be considered unstable.

2021-01-20 17:15 UTC, mulkieran requested changes
Looks good! Please close this and open a new PR for final review.

2021-01-20 17:57 UTC, closed without merging