Update bash completion
stratis-storage/stratis-cli pull request #710
Opened 2021-03-01 09:21 UTC by carzacc

Hi,

I've decided to give the Bash completion script another update to keep it up to date with changes to the CLI and fix a few issues with the script I've noticed while doing so.

The changes are:

* add `pool bind` and `pool unbind`
* only complete options for `pool create` when running `pool create`
* add `clevis` and `keyring` as completion options for `pool unlock`
* add the `--unhyphenated-uuids` option for listing

2021-03-01 14:09 UTC, mulkieran commented
ok to test

2021-03-01 16:23 UTC, drckeefe commented
Thank you for submitting this carzacc.  Looking at line 177, should there be a trailing "1" here?
"COMPREPLY=( $(compgen -W  "$(stratis pool list | awk '{if (NR!=1) {print $1}}')" -- ${cur}) )1"

Thank you for taking a look.

2021-03-01 19:46 UTC, carzacc commented
> Thank you for submitting this carzacc. Looking at line 177, should there be a trailing "1" here?
> "COMPREPLY=( $(compgen -W "$(stratis pool list | awk '{if (NR!=1) {print $1}}')" -- ${cur}) )1"
> 
> Thank you for taking a look.

oh no, that shouldn't be there, I'll remove that ASAP

2021-03-02 21:07 UTC, drckeefe commented
Manual testing of these changes passed on F34 with stratisd 2.4.0 
@poizen18 - Can you review this PR?

2021-03-04 20:23 UTC, drckeefe approved these changes

2021-03-04 20:24 UTC, drckeefe commented
Approved.  Thank you carzacc for the contribution.

2021-03-04 20:35 UTC, mulkieran requested changes
Thanks for PR. Please close this and open a final PR w/ just one commit. Much appreciated.

2021-03-05 08:58 UTC, closed without merging