Switch to literal string interpolation
stratis-storage/stratis-cli pull request #886
Opened 2022-05-13 18:52 UTC by bgurney-rh

Supersedes: #885
Related: stratis-storage/project#456

2022-05-13 23:25 UTC, mulkieran requested changes

2022-05-13 23:25 UTC, mulkieran commented on src/stratis_cli/_actions/_formatting.py
> +    return (
Copy-paste error here.

2022-05-31 17:54 UTC, mulkieran requested changes
Caught just one thing...

2022-05-31 17:54 UTC, mulkieran commented on src/stratis_cli/_error_reporting.py
> +                        f'interface "error.interface_name" to "{context.value}". '
Needs curly braces!

2022-05-31 19:58 UTC, bgurney-rh commented on src/stratis_cli/_error_reporting.py
> +                        f'interface "error.interface_name" to "{context.value}". '
Resolved.

2022-05-31 19:59 UTC, mulkieran approved these changes

2022-05-31 20:00 UTC, mulkieran commented
@bgurney-rh Plz rebase.

2022-05-31 20:03 UTC, bgurney-rh commented
Rebased.

2022-05-31 20:21 UTC, merged