Print Alert string in pool list detail view
stratis-storage/stratis-cli pull request #905
Opened 2022-08-17 21:36 UTC by bgurney-rh

Related: #903

2022-08-18 14:59 UTC, bgurney-rh commented
Example output (with an intentional WS001 alert):
```
$ stratis pool list --uuid=050a7855-ac20-4289-b1eb-19dc5f267f6a
UUID: 050a7855-ac20-4289-b1eb-19dc5f267f6a
Name: spool1
Alerts: WS001
Actions Allowed: fully_operational
Cache: No
...
```

2022-08-18 15:08 UTC, mulkieran reviewed
Looks good so far. The question now is, should we go with your proposal from https://github.com/stratis-storage/stratis-cli/issues/903#issuecomment-1217167634, or should we stay with this? @drckeefe might have an opinion also.

2022-08-18 15:47 UTC, bgurney-rh commented
I was sketching an idea of the PoolMaintenanceErrorCode errors, and PoolAllocSpaceErrorCode errors (from src/stratis_cli/_error_codes.py), to see if I could think of a shorter string to explain the current error codes:
```
WS001     NO_ALLOC_SPACE    All devices fully allocated
                "Every device belonging to the pool has been fully allocated. "
                "To increase the allocable space, add additional data devices "
                "to the pool."


EM001     NO_IPC_REQUESTS   Pool state changes not possible
                "The pool will return an error on any IPC request that could "
                "cause a change in the pool state, for example, a request to "
                "rename a filesystem. It will still be able to respond to "
                "purely informational requests."


EM002     NO_POOL_CHANGES   Pool maintenance operations not possible
                "The pool is unable to manage itself by reacting to events, "
                "such as devicemapper events, that might require it to take "
                "any maintenance operations."
```

2022-08-18 15:56 UTC, mulkieran commented
> I was sketching an idea of the PoolMaintenanceErrorCode errors, and PoolAllocSpaceErrorCode errors (from src/stratis_cli/_error_codes.py), to see if I could think of a shorter string to explain the current error codes:
> 
> ```
> WS001     NO_ALLOC_SPACE    All devices fully allocated
>                 "Every device belonging to the pool has been fully allocated. "
>                 "To increase the allocable space, add additional data devices "
>                 "to the pool."
> 
> 
> EM001     NO_IPC_REQUESTS   Pool state changes not possible
>                 "The pool will return an error on any IPC request that could "
>                 "cause a change in the pool state, for example, a request to "
>                 "rename a filesystem. It will still be able to respond to "
>                 "purely informational requests."
> 
> 
> EM002     NO_POOL_CHANGES   Pool maintenance operations not possible
>                 "The pool is unable to manage itself by reacting to events, "
>                 "such as devicemapper events, that might require it to take "
>                 "any maintenance operations."
> ```

It would be easy to add an additional short description along with the full description.

2022-08-18 17:45 UTC, drckeefe commented
I thought the truncated version was good, but I see in the version above there is a short description, which I  might be
better.   Here is an example.

$ stratis pool list --uuid=33123a6c-eb66-4c6f-9097-6b9521da4551
UUID: 33123a6c-eb66-4c6f-9097-6b9521da4551
Name: spool1
Alerts:
    WS001    All devices fully allocated
    EM001    Pool state changes not possible
    EM002    Pool maintenance operations not possible
Actions Allowed: fully_operational
Cache: No

Or it could be better to put all the alerts at the bottom of the output, especially if we want the full text version. 

$ stratis pool list --uuid=33123a6c-eb66-4c6f-9097-6b9521da4551
UUID: 33123a6c-eb66-4c6f-9097-6b9521da4551
Name: spool1
Actions Allowed: fully_operational
Cache: No
Alerts:
WS001     NO_ALLOC_SPACE    All devices fully allocated
                "Every device belonging to the pool has been fully allocated. "
                "To increase the allocable space, add additional data devices "
                "to the pool."

EM001     NO_IPC_REQUESTS   Pool state changes not possible
                "The pool will return an error on any IPC request that could "
                "cause a change in the pool state, for example, a request to "
                "rename a filesystem. It will still be able to respond to "
                "purely informational requests."

EM002     NO_POOL_CHANGES   Pool maintenance operations not possible
                "The pool is unable to manage itself by reacting to events, "
                "such as devicemapper events, that might require it to take "
                "any maintenance operations."

2022-08-23 15:19 UTC, mulkieran requested changes

2022-08-23 15:19 UTC, mulkieran commented on src/stratis_cli/_actions/_pool.py
> +        return (PoolErrorCode.summarize(code) for code in error_codes)
Try this line instead:

```
return os.linesep.join(code.summarize() for code in error_codes)
```

2022-08-23 15:28 UTC, bgurney-rh commented on src/stratis_cli/_error_codes.py
> +
I think this is still being used by the `stratis pool explain <error_code>` command.

2022-08-23 15:29 UTC, bgurney-rh commented on src/stratis_cli/_actions/_pool.py
> +        return (PoolErrorCode.summarize(code) for code in error_codes)
This seems to work; I now see this:
```
Alerts: All devices fully allocated
```

2022-08-26 19:02 UTC, mulkieran approved these changes

2022-08-26 19:05 UTC, bgurney-rh commented
Squashed into a single commit.

2022-08-26 19:24 UTC, merged