Fix tests for encrypted cache
stratis-storage/stratis-cli pull request #944
Opened 2022-12-12 19:40 UTC by jbaublitz

Related to stratis-storage/stratisd#3136

2022-12-13 14:12 UTC, mulkieran requested changes

2022-12-13 14:12 UTC, mulkieran commented on tests/whitebox/integration/pool/test_init_cache.py
> +        RUNNER(command_line)
^RUNNER^TEST_RUNNER

Please fix up comment.

2022-12-13 18:45 UTC, jbaublitz commented on tests/whitebox/integration/pool/test_init_cache.py
> +        RUNNER(command_line)
Resolved.

2022-12-14 02:17 UTC, mulkieran approved these changes

2022-12-15 17:59 UTC, mulkieran commented
@jbaublitz PLz put  a "pragma: no cover" annotation at the end of https://github.com/stratis-storage/stratis-cli/blob/master/src/stratis_cli/_actions/_pool.py#L316 to get the coverage to pass. We no longer have a way to elicit an engine error when creating a cache.

2022-12-15 18:21 UTC, merged