Add clevis_to_str function
stratis-storage/stratis-cli pull request #968
Opened 2023-03-16 21:59 UTC by bgurney-rh

Related: #958

2023-03-16 22:01 UTC, bgurney-rh commented
Example output:

tang (redacted):
```
Clevis Configuration: tang   thp: z_XXXXXXXXXXXXXX_XXX_XXXXXXXXXXXXXX-XXXXXXX url: http://127.0.0.1
```

TPM 2.0 (emulated):
```
Clevis Configuration: tpm2   
```

2023-03-16 23:00 UTC, mulkieran requested changes
Requesting one significant change.

2023-03-16 23:01 UTC, mulkieran commented
@bgurney-rh Note that we do not worry about coverage until the end; so it's ok if the coverage task keeps failing.

2023-03-17 18:21 UTC, bgurney-rh commented on src/stratis_cli/_actions/_utils.py
> +        self.config = " ".join(f"{key}: {value}" for key, value in config.items())
Resolved.

2023-03-28 14:59 UTC, mulkieran commented
@drckeefe Do you find the output format acceptable?

2023-03-28 18:04 UTC, drckeefe approved these changes

2023-03-28 19:10 UTC, mulkieran commented
@bgurney-rh Put ```no cover``` pragma's on both your newly introduced methods, like:

```
def clevis_to_str(clevis_dbus_object): # pragma: no cover
```

and run ```make fmt``` to get that formatted correctly.

It's going to be fairly hard to add tests, for fairly limited benefit, so just not trying to cover them is best, for now.

2023-03-28 19:10 UTC, mulkieran requested changes
Just add the ```no cover``` pragmas, squash it all into a single commit, and we can merge.

2023-03-28 19:37 UTC, bgurney-rh commented
All tests passed.  Squashing into a single commit.

2023-03-28 19:52 UTC, mulkieran approved these changes

2023-03-28 19:52 UTC, merged